### PR TITLE
Switched to SafariViewController to comply with the In-App Browser ban

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
> Work in progress (do not merge yet), I need to document the changes

Hi,

Sending this already for you to review. I will document the required changes in the readme. But that's really all there's left.

Eddy

### CODE REVIEW

**Comment by PeterStaev** [comment]
Hey @EddyVerbruggen , it looks great!. Have one question though - is it really needed we require the user to manually set the delegate? How about we do it internally in the `if` where you reject the login [here](https://github.com/PeterStaev/nativescript-azure-mobile-apps/pull/14/files#diff-44aa018e5db3abf91b0b1b926585cb32R48)? Won't this be a better option and should still work?

**Comment by EddyVerbruggen** [comment]
Hey Peter,

I wondered the same and tried and tried and tried but it seems you must really wire the appdelegate before the app is started. I had a similar experience with my Firebase and 3D Touch plugins.

It could be simplified to only a `require` and do the delegate assignment in the required plugin file, but I'm afraid we need the user to add that line.

There is an alternative but I'm not intending to do that now: add a native library that swizzles the required appdelegate methods and ship it with the plugin.

**Comment by PeterStaev** [comment]
True. Seems related to this: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application/application.ios.ts#L285 I guess Apple did not account for users to be able to change the AppDelegate during runtime and they require you to specify it when you start the app 😄

**Comment by PeterStaev** [comment]
Thinking more about this, how about we add static function in the root module of the plugin that will do the delegate registration? We can have a dummy android file with the function doing nothing. This way the user will not have to do a check for platform and will just have to call the function before `application.start()`. Thoughts?

**Comment by EddyVerbruggen** [comment]
Hey Peter, indeed. That's kinda what I meant by "It could be simplified to only a require and do the delegate assignment in the required plugin file, but I'm afraid we need the user to add that line." but you've thought it a bit more through.

Let me take a stab at that tonight or this weekend.

**Comment by EddyVerbruggen** [comment]
iOS AppDelegate wiring has been refactored. Still need to do the doc 😄

**Comment by EddyVerbruggen** [comment]
Docs are done. It should be good to merge. I've seen travis failing on previous commits and it seemed unrelated to this PR really, but not sure. Can you look at those please?

**Comment by PeterStaev** [comment]
Thanks @EddyVerbruggen ! I will merge a bit later and will see to fix Travis (I think i know what is the problem)

**Pull request merged**
